baseURL = "http://lucasblacklu.github.io/"
DefaultContentLanguage = "zh-hant" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-hant"
title = "Hugo 網站"
copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = true
enableAutoDarkMode=true


# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "BlackLu Blog" # will set 'og:site_name'
description = "心之所願，無所不成"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "分類"
weight = 2
[[menu.main]]
url = "/tags"	
name = "標籤"
weight = 3
[[menu.main]]
url = "/posts"
name = "文章"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

googleAnalytics = "UA-123-45"
